package com.oscinnovation.fitness.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CircuitoToEsercizioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCircuitoToEsercizioAllPropertiesEquals(CircuitoToEsercizio expected, CircuitoToEsercizio actual) {
        assertCircuitoToEsercizioAutoGeneratedPropertiesEquals(expected, actual);
        assertCircuitoToEsercizioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCircuitoToEsercizioAllUpdatablePropertiesEquals(CircuitoToEsercizio expected, CircuitoToEsercizio actual) {
        assertCircuitoToEsercizioUpdatableFieldsEquals(expected, actual);
        assertCircuitoToEsercizioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCircuitoToEsercizioAutoGeneratedPropertiesEquals(CircuitoToEsercizio expected, CircuitoToEsercizio actual) {
        assertThat(expected)
            .as("Verify CircuitoToEsercizio auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCircuitoToEsercizioUpdatableFieldsEquals(CircuitoToEsercizio expected, CircuitoToEsercizio actual) {
        assertThat(expected)
            .as("Verify CircuitoToEsercizio relevant properties")
            .satisfies(e -> assertThat(e.getReps()).as("check reps").isEqualTo(actual.getReps()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCircuitoToEsercizioUpdatableRelationshipsEquals(CircuitoToEsercizio expected, CircuitoToEsercizio actual) {
        assertThat(expected)
            .as("Verify CircuitoToEsercizio relationships")
            .satisfies(e -> assertThat(e.getEsercizio()).as("check esercizio").isEqualTo(actual.getEsercizio()))
            .satisfies(e -> assertThat(e.getCircuito()).as("check circuito").isEqualTo(actual.getCircuito()));
    }
}
