package com.oscinnovation.fitness.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CorsaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsaAllPropertiesEquals(Corsa expected, Corsa actual) {
        assertCorsaAutoGeneratedPropertiesEquals(expected, actual);
        assertCorsaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsaAllUpdatablePropertiesEquals(Corsa expected, Corsa actual) {
        assertCorsaUpdatableFieldsEquals(expected, actual);
        assertCorsaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsaAutoGeneratedPropertiesEquals(Corsa expected, Corsa actual) {
        assertThat(expected)
            .as("Verify Corsa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsaUpdatableFieldsEquals(Corsa expected, Corsa actual) {
        assertThat(expected)
            .as("Verify Corsa relevant properties")
            .satisfies(e ->
                assertThat(e.getDistanzaDaPercorrere()).as("check distanzaDaPercorrere").isEqualTo(actual.getDistanzaDaPercorrere())
            )
            .satisfies(e -> assertThat(e.getTempoImpiegato()).as("check tempoImpiegato").isEqualTo(actual.getTempoImpiegato()))
            .satisfies(e -> assertThat(e.getSvolto()).as("check svolto").isEqualTo(actual.getSvolto()))
            .satisfies(e -> assertThat(e.getCompletato()).as("check completato").isEqualTo(actual.getCompletato()))
            .satisfies(e -> assertThat(e.getFeedback()).as("check feedback").isEqualTo(actual.getFeedback()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsaUpdatableRelationshipsEquals(Corsa expected, Corsa actual) {
        assertThat(expected)
            .as("Verify Corsa relationships")
            .satisfies(e ->
                assertThat(e.getAllenamentoGiornaliero()).as("check allenamentoGiornaliero").isEqualTo(actual.getAllenamentoGiornaliero())
            );
    }
}
