package com.oscinnovation.fitness.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CorsoAcademyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsoAcademyAllPropertiesEquals(CorsoAcademy expected, CorsoAcademy actual) {
        assertCorsoAcademyAutoGeneratedPropertiesEquals(expected, actual);
        assertCorsoAcademyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsoAcademyAllUpdatablePropertiesEquals(CorsoAcademy expected, CorsoAcademy actual) {
        assertCorsoAcademyUpdatableFieldsEquals(expected, actual);
        assertCorsoAcademyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsoAcademyAutoGeneratedPropertiesEquals(CorsoAcademy expected, CorsoAcademy actual) {
        assertThat(expected)
            .as("Verify CorsoAcademy auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsoAcademyUpdatableFieldsEquals(CorsoAcademy expected, CorsoAcademy actual) {
        assertThat(expected)
            .as("Verify CorsoAcademy relevant properties")
            .satisfies(e -> assertThat(e.getLivello()).as("check livello").isEqualTo(actual.getLivello()))
            .satisfies(e -> assertThat(e.getTitolo()).as("check titolo").isEqualTo(actual.getTitolo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorsoAcademyUpdatableRelationshipsEquals(CorsoAcademy expected, CorsoAcademy actual) {
        // empty method
    }
}
