package com.oscinnovation.fitness.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PassaggioEsercizioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassaggioEsercizioAllPropertiesEquals(PassaggioEsercizio expected, PassaggioEsercizio actual) {
        assertPassaggioEsercizioAutoGeneratedPropertiesEquals(expected, actual);
        assertPassaggioEsercizioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassaggioEsercizioAllUpdatablePropertiesEquals(PassaggioEsercizio expected, PassaggioEsercizio actual) {
        assertPassaggioEsercizioUpdatableFieldsEquals(expected, actual);
        assertPassaggioEsercizioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassaggioEsercizioAutoGeneratedPropertiesEquals(PassaggioEsercizio expected, PassaggioEsercizio actual) {
        assertThat(expected)
            .as("Verify PassaggioEsercizio auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassaggioEsercizioUpdatableFieldsEquals(PassaggioEsercizio expected, PassaggioEsercizio actual) {
        assertThat(expected)
            .as("Verify PassaggioEsercizio relevant properties")
            .satisfies(e -> assertThat(e.getIndice()).as("check indice").isEqualTo(actual.getIndice()))
            .satisfies(e -> assertThat(e.getDescrizione()).as("check descrizione").isEqualTo(actual.getDescrizione()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassaggioEsercizioUpdatableRelationshipsEquals(PassaggioEsercizio expected, PassaggioEsercizio actual) {
        assertThat(expected)
            .as("Verify PassaggioEsercizio relationships")
            .satisfies(e -> assertThat(e.getEsercizio()).as("check esercizio").isEqualTo(actual.getEsercizio()));
    }
}
